<a href="https://colab.research.google.com/github/tanmay023/GREEN-SKILL-AND-AI/blob/main/day3_shell_india.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


In [ ]:
DataFrame = pd.read_csv('nba.csv')
print(DataFrame)


              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Ma

In [ ]:
DataFrame.describe()

Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [ ]:
DataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      457 non-null    object 
 1   Team      457 non-null    object 
 2   Number    457 non-null    float64
 3   Position  457 non-null    object 
 4   Age       457 non-null    float64
 5   Height    457 non-null    object 
 6   Weight    457 non-null    float64
 7   College   373 non-null    object 
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB


In [ ]:
DataFrame.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [ ]:
DataFrame.isnull()

Name   Team  Number  Position    Age  Height  Weight  College  Salary
0    False  False   False     False  False   False   False    False   False
1    False  False   False     False  False   False   False    False   False
2    False  False   False     False  False   False   False    False    True
3    False  False   False     False  False   False   False    False   False
4    False  False   False     False  False   False   False     True   False
..     ...    ...     ...       ...    ...     ...     ...      ...     ...
453  False  False   False     False  False   False   False    False   False
454  False  False   False     False  False   False   False     True   False
455  False  False   False     False  False   False   False     True   False
456  False  False   False     False  False   False   False    False   False
457   True   True    True      True   True    True    True     True    True

[458 rows x 9 columns]

In [ ]:
DataFrame.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [ ]:
DataFrame.isna()

Name   Team  Number  Position    Age  Height  Weight  College  Salary
0    False  False   False     False  False   False   False    False   False
1    False  False   False     False  False   False   False    False   False
2    False  False   False     False  False   False   False    False    True
3    False  False   False     False  False   False   False    False   False
4    False  False   False     False  False   False   False     True   False
..     ...    ...     ...       ...    ...     ...     ...      ...     ...
453  False  False   False     False  False   False   False    False   False
454  False  False   False     False  False   False   False     True   False
455  False  False   False     False  False   False   False     True   False
456  False  False   False     False  False   False   False    False   False
457   True   True    True      True   True    True    True     True    True

[458 rows x 9 columns]

In [ ]:
DataFrame.isna().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [ ]:
DataFrame['Name'].unique()

array(['Avery Bradley', 'Jae Crowder', 'John Holland', 'R.J. Hunter',
       'Jonas Jerebko', 'Amir Johnson', 'Jordan Mickey', 'Kelly Olynyk',
       'Terry Rozier', 'Marcus Smart', 'Jared Sullinger', 'Isaiah Thomas',
       'Evan Turner', 'James Young', 'Tyler Zeller', 'Bojan Bogdanovic',
       'Markel Brown', 'Wayne Ellington', 'Rondae Hollis-Jefferson',
       'Jarrett Jack', 'Sergey Karasev', 'Sean Kilpatrick',
       'Shane Larkin', 'Brook Lopez', 'Chris McCullough', 'Willie Reed',
       'Thomas Robinson', 'Henry Sims', 'Donald Sloan', 'Thaddeus Young',
       'Arron Afflalo', 'Lou Amundson', 'Thanasis Antetokounmpo',
       'Carmelo Anthony', 'Jose Calderon', 'Cleanthony Early',
       'Langston Galloway', 'Jerian Grant', 'Robin Lopez', "Kyle O'Quinn",
       'Kristaps Porzingis', 'Kevin Seraphin', 'Lance Thomas',
       'Sasha Vujacic', 'Derrick Williams', 'Tony Wroten', 'Elton Brand',
       'Isaiah Canaan', 'Robert Covington', 'Joel Embiid', 'Jerami Grant',
       'Richaun H

In [ ]:
DataFrame['Name'].nunique()

457

In [ ]:
DataFrame.loc[0:21,["Name","Team"]]

Name            Team
0             Avery Bradley  Boston Celtics
1               Jae Crowder  Boston Celtics
2              John Holland  Boston Celtics
3               R.J. Hunter  Boston Celtics
4             Jonas Jerebko  Boston Celtics
5              Amir Johnson  Boston Celtics
6             Jordan Mickey  Boston Celtics
7              Kelly Olynyk  Boston Celtics
8              Terry Rozier  Boston Celtics
9              Marcus Smart  Boston Celtics
10          Jared Sullinger  Boston Celtics
11            Isaiah Thomas  Boston Celtics
12              Evan Turner  Boston Celtics
13              James Young  Boston Celtics
14             Tyler Zeller  Boston Celtics
15         Bojan Bogdanovic   Brooklyn Nets
16             Markel Brown   Brooklyn Nets
17          Wayne Ellington   Brooklyn Nets
18  Rondae Hollis-Jefferson   Brooklyn Nets
19             Jarrett Jack   Brooklyn Nets
20           Sergey Karasev   Brooklyn Nets
21          Sean Kilpatrick   Brooklyn Nets

In [ ]:
DataFrame.iloc[90:100,0:3] #Accessing using INDEX And "8" is excluded here

Name                   Team  Number
90          Anderson Varejao  Golden State Warriors    18.0
91              Cole Aldrich   Los Angeles Clippers    45.0
92                Jeff Ayres   Los Angeles Clippers    19.0
93            Jamal Crawford   Los Angeles Clippers    11.0
94            Branden Dawson   Los Angeles Clippers    22.0
95                Jeff Green   Los Angeles Clippers     8.0
96             Blake Griffin   Los Angeles Clippers    32.0
97            Wesley Johnson   Los Angeles Clippers    33.0
98            DeAndre Jordan   Los Angeles Clippers     6.0
99  Luc Richard Mbah a Moute   Los Angeles Clippers    12.0

In [ ]:
import pandas as pd
DataFrame = pd.read_csv('nba.csv')
DataFrame.iloc[90:100,0:4]

Name                   Team  Number Position
90          Anderson Varejao  Golden State Warriors    18.0       PF
91              Cole Aldrich   Los Angeles Clippers    45.0        C
92                Jeff Ayres   Los Angeles Clippers    19.0       PF
93            Jamal Crawford   Los Angeles Clippers    11.0       SG
94            Branden Dawson   Los Angeles Clippers    22.0       SF
95                Jeff Green   Los Angeles Clippers     8.0       SF
96             Blake Griffin   Los Angeles Clippers    32.0       PF
97            Wesley Johnson   Los Angeles Clippers    33.0       SF
98            DeAndre Jordan   Los Angeles Clippers     6.0        C
99  Luc Richard Mbah a Moute   Los Angeles Clippers    12.0       PF

In [ ]:
DataFrame.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [ ]:
sub_df = DataFrame[['Name', 'Team', 'Number','College']]

In [ ]:
print(sub_df)

              Name            Team  Number            College
0    Avery Bradley  Boston Celtics     0.0              Texas
1      Jae Crowder  Boston Celtics    99.0          Marquette
2     John Holland  Boston Celtics    30.0  Boston University
3      R.J. Hunter  Boston Celtics    28.0      Georgia State
4    Jonas Jerebko  Boston Celtics     8.0                NaN
..             ...             ...     ...                ...
453   Shelvin Mack       Utah Jazz     8.0             Butler
454      Raul Neto       Utah Jazz    25.0                NaN
455   Tibor Pleiss       Utah Jazz    21.0                NaN
456    Jeff Withey       Utah Jazz    24.0             Kansas
457            NaN             NaN     NaN                NaN

[458 rows x 4 columns]


In [ ]:
DataFrame[DataFrame["College"]=='Texas']

Name                   Team  Number Position   Age Height  \
0        Avery Bradley         Boston Celtics     0.0       PG  25.0    6-2   
66         Cory Joseph        Toronto Raptors     6.0       PG  24.0    6-3   
133        P.J. Tucker           Phoenix Suns    17.0       SF  31.0    6-6   
179   Tristan Thompson    Cleveland Cavaliers    13.0        C  25.0    6-9   
208       Myles Turner         Indiana Pacers    33.0       PF  20.0   6-11   
289    Jordan Hamilton   New Orleans Pelicans    25.0       SG  25.0    6-7   
294  LaMarcus Aldridge      San Antonio Spurs    12.0       PF  30.0   6-11   
384      D.J. Augustin         Denver Nuggets    12.0       PG  28.0    6-0   
414       Kevin Durant  Oklahoma City Thunder    35.0       SF  27.0    6-9   

     Weight College      Salary  
0     180.0   Texas   7730337.0  
66    190.0   Texas   7000000.0  
133   245.0   Texas   5500000.0  
179   238.0   Texas  14260870.0  
208   243.0   Texas   2357760.0  
289   220.0   Texas   1015421.0  
294   240.0   Texas  19689000.0  
384   183.0   Texas   3000000.0  
414   240.0   Texas  20158622.0

In [ ]:
DataFrame['College'].unique()

array(['Texas', 'Marquette', 'Boston University', 'Georgia State', nan,
       'LSU', 'Gonzaga', 'Louisville', 'Oklahoma State', 'Ohio State',
       'Washington', 'Kentucky', 'North Carolina', 'Arizona',
       'Georgia Tech', 'Cincinnati', 'Miami (FL)', 'Stanford', 'Syracuse',
       'Saint Louis', 'Kansas', 'Georgetown', 'Texas A&M', 'UCLA', 'UNLV',
       'Wichita State', "Saint Joseph's", 'Notre Dame', 'Norfolk State',
       'Duke', 'Murray State', 'Tennessee State', 'Bowling Green',
       'Purdue', 'Wake Forest', 'Michigan', 'Missouri', 'USC',
       'Villanova', 'Rider', 'Utah', 'Belmont', 'Davidson', 'Vanderbilt',
       'Michigan State', 'Florida', 'Washington State', 'Arizona State',
       'Oklahoma', 'Wyoming', "St. John's", 'Maryland', 'Wisconsin',
       'Utah Valley', 'North Carolina State', 'UC Santa Barbara',
       'Baylor', 'Connecticut', 'Oregon State', 'New Mexico', 'Oregon',
       'Creighton', 'Arkansas', 'Memphis', "Saint Mary's", 'Tennessee',
       'Alabama'

In [ ]:
DataFrame[DataFrame["College"]=="Kansas"]

Name                    Team  Number Position   Age Height  \
26   Thomas Robinson           Brooklyn Nets    41.0       PF  25.0   6-10   
49       Joel Embiid      Philadelphia 76ers    21.0        C  22.0    7-0   
87      Brandon Rush   Golden State Warriors     4.0       SF  30.0    6-6   
91      Cole Aldrich    Los Angeles Clippers    45.0        C  27.0   6-11   
101      Paul Pierce    Los Angeles Clippers    34.0       SF  38.0    6-7   
107      Tarik Black      Los Angeles Lakers    28.0        C  24.0    6-9   
148     Ben McLemore        Sacramento Kings    23.0       SG  23.0    6-5   
173       Sasha Kaun     Cleveland Cavaliers    14.0        C  31.0   6-11   
194    Marcus Morris         Detroit Pistons    13.0       PF  26.0    6-9   
311     Kirk Hinrich           Atlanta Hawks    12.0       SG  35.0    6-4   
372      Drew Gooden      Washington Wizards    90.0       PF  34.0   6-10   
376  Markieff Morris      Washington Wizards     5.0       PF  26.0   6-10   
377  Kelly Oubre Jr.      Washington Wizards    12.0       SF  20.0    6-7   
383   Darrell Arthur          Denver Nuggets     0.0       PF  28.0    6-9   
411   Andrew Wiggins  Minnesota Timberwolves    22.0       SG  21.0    6-8   
413    Nick Collison   Oklahoma City Thunder     4.0       PF  35.0   6-10   
427  Cliff Alexander  Portland Trail Blazers    34.0       PF  20.0    6-8   
456      Jeff Withey               Utah Jazz    24.0        C  26.0    7-0   

     Weight College     Salary  
26    237.0  Kansas   981348.0  
49    250.0  Kansas  4626960.0  
87    220.0  Kansas  1270964.0  
91    250.0  Kansas  1100602.0  
101   235.0  Kansas  3376000.0  
107   250.0  Kansas   845059.0  
148   195.0  Kansas  3156600.0  
173   260.0  Kansas  1276000.0  
194   235.0  Kansas  5000000.0  
311   190.0  Kansas  2854940.0  
372   250.0  Kansas  3300000.0  
376   245.0  Kansas  8000000.0  
377   205.0  Kansas  1920240.0  
383   235.0  Kansas  2814000.0  
411   199.0  Kansas  5758680.0  
413   255.0  Kansas  3750000.0  
427   240.0  Kansas   525093.0  
456   231.0  Kansas   947276.0

In [ ]:
DataFrame[DataFrame['Position']=="PF"]

Name                    Team  Number Position   Age Height  \
4       Jonas Jerebko          Boston Celtics     8.0       PF  29.0   6-10   
5        Amir Johnson          Boston Celtics    90.0       PF  29.0    6-9   
6       Jordan Mickey          Boston Celtics    55.0       PF  21.0    6-8   
24   Chris McCullough           Brooklyn Nets     1.0       PF  21.0   6-11   
25        Willie Reed           Brooklyn Nets    33.0       PF  26.0   6-10   
..                ...                     ...     ...      ...   ...    ...   
435    Meyers Leonard  Portland Trail Blazers    11.0       PF  24.0    7-1   
441       Noah Vonleh  Portland Trail Blazers    21.0       PF  20.0    6-9   
442     Trevor Booker               Utah Jazz    33.0       PF  28.0    6-8   
446    Derrick Favors               Utah Jazz    15.0       PF  24.0   6-10   
452        Trey Lyles               Utah Jazz    41.0       PF  20.0   6-10   

     Weight       College      Salary  
4     231.0           NaN   5000000.0  
5     240.0           NaN  12000000.0  
6     235.0           LSU   1170960.0  
24    200.0      Syracuse   1140240.0  
25    220.0   Saint Louis    947276.0  
..      ...           ...         ...  
435   245.0      Illinois   3075880.0  
441   240.0       Indiana   2637720.0  
442   228.0       Clemson   4775000.0  
446   265.0  Georgia Tech  12000000.0  
452   234.0      Kentucky   2239800.0  

[100 rows x 9 columns]

In [ ]:
df_filtered = DataFrame[(DataFrame["College"]=='Texas') & (DataFrame['Age']<25)]
df_filtered

Name             Team  Number Position   Age Height  Weight  \
66    Cory Joseph  Toronto Raptors     6.0       PG  24.0    6-3   190.0   
208  Myles Turner   Indiana Pacers    33.0       PF  20.0   6-11   243.0   

    College     Salary  
66    Texas  7000000.0  
208   Texas  2357760.0

In [ ]:
df_filter = DataFrame[DataFrame["College"]=='Boston University']
df_filter

Name            Team  Number Position   Age Height  Weight  \
2  John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   

             College  Salary  
2  Boston University     NaN

In [ ]:
df_filter = DataFrame[(DataFrame["College"]=='Boston University')&(DataFrame['Age']>25)]
df_filter

Name            Team  Number Position   Age Height  Weight  \
2  John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   

             College  Salary  
2  Boston University     NaN

In [ ]:
DataFrame.query('Age > 30')

Name                    Team  Number Position   Age Height  \
19      Jarrett Jack           Brooklyn Nets     2.0       PG  32.0    6-3   
31      Lou Amundson         New York Knicks    17.0       PF  33.0    6-9   
33   Carmelo Anthony         New York Knicks     7.0       SF  32.0    6-8   
34     Jose Calderon         New York Knicks     3.0       PG  34.0    6-3   
43     Sasha Vujacic         New York Knicks    18.0       SG  32.0    6-7   
..               ...                     ...     ...      ...   ...    ...   
406  Tayshaun Prince  Minnesota Timberwolves    12.0       SF  36.0    6-9   
413    Nick Collison   Oklahoma City Thunder     4.0       PF  35.0   6-10   
415       Randy Foye   Oklahoma City Thunder     6.0       SG  32.0    6-4   
420    Nazr Mohammed   Oklahoma City Thunder    13.0        C  38.0   6-10   
434      Chris Kaman  Portland Trail Blazers    35.0        C  34.0    7-0   

     Weight           College      Salary  
19    200.0      Georgia Tech   6300000.0  
31    220.0              UNLV   1635476.0  
33    240.0          Syracuse  22875000.0  
34    200.0               NaN   7402812.0  
43    195.0               NaN    947276.0  
..      ...               ...         ...  
406   212.0          Kentucky    947276.0  
413   255.0            Kansas   3750000.0  
415   213.0         Villanova   3135000.0  
420   250.0          Kentucky    222888.0  
434   265.0  Central Michigan   5016000.0  

[91 rows x 9 columns]

In [ ]:
clean_df = DataFrame.dropna(axis=0,how="any") #axis represents 0 - ROWS, 1 - COLUMNS any - ATLEAST 1 missing value
clean_df

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
6    Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0   
7     Kelly Olynyk  Boston Celtics    41.0        C  25.0    7-0   238.0   
..             ...             ...     ...      ...   ...    ...     ...   
449    Rodney Hood       Utah Jazz     5.0       SG  23.0    6-8   206.0   
451  Chris Johnson       Utah Jazz    23.0       SF  26.0    6-6   206.0   
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   

           College     Salary  
0            Texas  7730337.0  
1        Marquette  6796117.0  
3    Georgia State  1148640.0  
6              LSU  1170960.0  
7          Gonzaga  2165160.0  
..             ...        ...  
449           Duke  1348440.0  
451         Dayton   981348.0  
452       Kentucky  2239800.0  
453         Butler  2433333.0  
456         Kansas   947276.0  

[364 rows x 9 columns]

In [ ]:
clean_df=DataFrame.dropna(axis=0,thresh=8) # (threshold)-minimum requirement rows if less than 8 missing values are there then values will drop
clean_df

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
452     Trey Lyles       Utah Jazz    41.0       PF  20.0   6-10   234.0   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
452           Kentucky  2239800.0  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  

[455 rows x 9 columns]

In [ ]:
DataFrame['Salary'].isnull()

0      False
1      False
2       True
3      False
4      False
       ...  
453    False
454    False
455    False
456    False
457     True
Name: Salary, Length: 458, dtype: bool

In [ ]:
DataFrame['Salary'].isnull().sum()


np.int64(12)

In [ ]:
avg_salary = DataFrame['Salary'].mean()
avg_salary

np.float64(4842684.105381166)

In [ ]:
import warnings as war
war.filterwarnings("ignore")

In [ ]:
DataFrame['Salary'].fillna(avg_salary,inplace=True)

In [ ]:
DataFrame['Salary'].isnull().sum()

np.int64(0)

In [ ]:
data = {
    'Name':['Aman','Ram','Aman','Ram','Aman'],
    'Age':[27,24,27,24,19],
    'city':['Haryana','Surart','Haryana','New Delhi','Rajkot']
}
dataframe = pd.DataFrame(data)
dataframe

Name  Age       city
0  Aman   27    Haryana
1   Ram   24     Surart
2  Aman   27    Haryana
3   Ram   24  New Delhi
4  Aman   19     Rajkot

In [ ]:
dataframe.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [ ]:
dataframe.duplicated().sum()

np.int64(1)

In [ ]:
print(dataframe.duplicated(subset=['Name','Age']))

0    False
1    False
2     True
3     True
4    False
dtype: bool


In [ ]:
dataframe.drop_duplicates(subset=['Name','Age'],inplace=True)

In [ ]:
dataframe

Name  Age     city
0  Aman   27  Haryana
1   Ram   24   Surart
4  Aman   19   Rajkot

In [ ]:
dataframe.dropna(axis=0,inplace=True)
dataframe.shape

(3, 3)

In [ ]:
DataFrame.dropna(axis=0,inplace=True)
DataFrame.shape

(373, 9)

In [ ]:
result = DataFrame.groupby("College")
result

In [ ]:
result.get_group("Texas")

Name                   Team  Number Position   Age Height  \
0        Avery Bradley         Boston Celtics     0.0       PG  25.0    6-2   
66         Cory Joseph        Toronto Raptors     6.0       PG  24.0    6-3   
133        P.J. Tucker           Phoenix Suns    17.0       SF  31.0    6-6   
179   Tristan Thompson    Cleveland Cavaliers    13.0        C  25.0    6-9   
208       Myles Turner         Indiana Pacers    33.0       PF  20.0   6-11   
289    Jordan Hamilton   New Orleans Pelicans    25.0       SG  25.0    6-7   
294  LaMarcus Aldridge      San Antonio Spurs    12.0       PF  30.0   6-11   
384      D.J. Augustin         Denver Nuggets    12.0       PG  28.0    6-0   
414       Kevin Durant  Oklahoma City Thunder    35.0       SF  27.0    6-9   

     Weight College      Salary  
0     180.0   Texas   7730337.0  
66    190.0   Texas   7000000.0  
133   245.0   Texas   5500000.0  
179   238.0   Texas  14260870.0  
208   243.0   Texas   2357760.0  
289   220.0   Texas   1015421.0  
294   240.0   Texas  19689000.0  
384   183.0   Texas   3000000.0  
414   240.0   Texas  20158622.0

In [ ]:
result['Age'].mean()

College
Alabama             29.000000
Arizona             27.384615
Arizona State       27.500000
Arkansas            27.333333
Baylor              25.000000
                      ...    
Western Michigan    25.000000
Wichita State       25.000000
Wisconsin           25.800000
Wyoming             23.000000
Xavier              35.000000
Name: Age, Length: 118, dtype: float64

In [ ]:
result['Age'].mean().sort_values(ascending=True)

College
Bowling Green          22.0
Georgia State          22.0
Louisiana-Lafayette    22.0
Iowa State             23.0
Georgia                23.0
                       ... 
Utah Valley            32.0
Western Carolina       33.0
Central Michigan       34.0
Xavier                 35.0
Blinn College          37.0
Name: Age, Length: 118, dtype: float64

In [ ]:
count_college_wise = result["Team"].count()
count_college_wise

College
Alabama              3
Arizona             13
Arizona State        2
Arkansas             3
Baylor               1
                    ..
Western Michigan     1
Wichita State        1
Wisconsin            5
Wyoming              1
Xavier               1
Name: Team, Length: 118, dtype: int64

In [ ]:
result.agg(
    avg_age = ("Age","mean"),
    max_age = ("Age","max"),
    min_age = ("Age","min"),
    count_team = ("Team","count")
)

avg_age  max_age  min_age  count_team
College                                                  
Alabama           29.000000     33.0     25.0           3
Arizona           27.384615     38.0     20.0          13
Arizona State     27.500000     29.0     26.0           2
Arkansas          27.333333     34.0     21.0           3
Baylor            25.000000     25.0     25.0           1
...                     ...      ...      ...         ...
Western Michigan  25.000000     25.0     25.0           1
Wichita State     25.000000     25.0     25.0           1
Wisconsin         25.800000     33.0     22.0           5
Wyoming           23.000000     23.0     23.0           1
Xavier            35.000000     35.0     35.0           1

[118 rows x 4 columns]

In [ ]:
DATA = {
    'Math':[90,85,98,80,55,78],
    'Science':[92,87,59,64,87,96],
    'English':[95,94,84,75,67,65]
}

df = pd.DataFrame(DATA)
df

Math  Science  English
0    90       92       95
1    85       87       94
2    98       59       84
3    80       64       75
4    55       87       67
5    78       96       65

In [ ]:
df.sum()

Math       486
Science    485
English    480
dtype: int64

In [ ]:
df.mean()

Math       81.000000
Science    80.833333
English    80.000000
dtype: float64

In [ ]:
df.max()

Math       98
Science    96
English    95
dtype: int64

In [ ]:
df.median()

Math       82.5
Science    87.0
English    79.5
dtype: float64

In [ ]:
import numpy as np
mylist = [[1,2,3],[4,5,6],[7,8,9]]
np.array(mylist)
print(mylist)

print(np.random.rand(5))
print(np.random.rand(4,4))
np.random.randn(4)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[0.00689907 0.29105786 0.39330987 0.04770867 0.66940037]
[[0.5164606  0.97948215 0.55172325 0.26196591]
 [0.33280839 0.08871943 0.78865611 0.40948782]
 [0.65033082 0.02528564 0.90765785 0.36458945]
 [0.60531523 0.06637743 0.91924897 0.25972123]]


array([ 0.71781713,  0.51131467,  0.38060652, -0.66505359])

#Boxcox and Yo-Jhonson used for converting data to normalised form

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])